Feature/ posts/:companyId
alejodelosrios/Henry-Bootcamp-FP pull request #20
Opened 2022-01-19 21:56 UTC by celesmedina

- Creación de la ruta get de post/:companyId
- Hice varios cambios en el código propios de TypeScript
- Agregué relaciones al modelo de la base de datos

2022-01-19 22:10 UTC, alejodelosrios requested changes
Hola @celesmedina, de acuerdo al objeto posts que envió @bryan-delacruz, se debe actualizar el postController

2022-01-19 22:19 UTC, Ridegras approved these changes
Okey... Tendría que meterme en prisma para entender un poco más pero se ve correcto.
Al final, como dice Ale, hay que ver si le agregamos category al postController..
Lo único que recomendaría es tratar de hacer PR mas cortos, no sé que opina el resto..
Todo genial! :)

2022-01-20 14:42 UTC, Carolinaortiz95 approved these changes
Corregido el modelo post, agregada ruta post/create

2022-01-20 14:44 UTC, alejodelosrios approved these changes
Correctos los cambios

2022-01-20 14:45 UTC, merged